### PR TITLE
Chinese translation. 

### PR DESCRIPTION
**Pull request by rtxyd**
I made a Chinese translation. Several words may be inaccurate. But I think for a normal Chinese, that's enough to understand. 
Then there's a question, I translate "order" to "order of regularity" instead of "order of ranks", is that right?

### CODE REVIEW

**Comment by rtxyd** [comment]
Good mod. My friends can't read english, so I translated it. Glad that you merged it.

**Comment by WuzgXY-GitHub** [comment]
机翻，请自重。

**Comment by rtxyd** [comment]
@WuzgXY-GitHub @Lach01298 It is ashamed to say that I made the translation half by machine, and it's just my personal translation, but I fixed those parts which was not fluent, to make it understandable.  Hope I didn't make you angry. As I said in description, I thought it is enough for a normal Chinese to understand what these things are and how to use them. **All I want to do is making an early translation that could be suitable for as many as people**. I am just a student, not professional translator, maybe his translation is better. I am really sorry.

**Comment by Lach01298** [comment]
It's alright I don't know why WuzgXY was very defensive about it.

**Comment by WuzgXY-GitHub** [comment]
> It's alright I don't know why WuzgXY was very defensive about it.

Not defensive, but I just think one should be responsible to his work. It would be shown to every Chinese player who has installed this mod as a translation, and I believe nobody would like to play with machine-translation. He has apologized for his behavior in somewhere else, and it’s okay then. Sorry for showing defensive, I just don’t know how to express clearly what I mean sometimes, especially in another language >_<

**Comment by rtxyd** [comment]
@WuzgXY-GitHub I've seen som parts of your translation, I have some suggestions. 
  Personally, I think some of them may not better than before. Like "partical chamber", **"粒子间", normally, it's "粒子室" for a particle accelerator**, so as **"target chamber" as "靶室"**. And **"focus", "聚焦" (也许我翻译错了) , I think it's "焦点"**, because it's not fluent and for an accelerator, there need a focus to shoot particals at. And "The Z and W bosons are the carries of the weak force. The weak force is what allows some particles to decay and is responsible for beta decay", "Z和W玻色子是弱力的载体。弱力制约放射性衰变，并是β衰变的原因。"This part makes me confused, the origional says **"The weak force is what allows some particles to decay", literally "弱作用力是允许某些粒子衰变的力。" but there it says "weak force constrains radiation decay".** And **"enchantability" is "附魔性"**. And for "alpha",  I recommend to use Greek character. 
  Maybe it could be better in some ways. And now you are official translator admited by author, you take the charge. 
  Since I do translation because of interest, it seems I won't have a chance to make another translation 'cause I will still refer to translate apps. 
  Good luck.

**Comment by WuzgXY-GitHub** [comment]
@rtxyd 愿意加下QQ讨论吗？1654099550

**Comment by rtxyd** [comment]
@WuzgXY-GitHub 抱歉，我的水平并不高，我不太喜欢这样。

**Pull request merged**
